runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: frontend/public/index.html
  upload: frontend/public/index.html

- url: /auth
  script: main.app

- url: /logout
  script: main.app

- url: /accounts
  script: main.app

- url: /sendAward
  script: main.app

- url: /api/awards
  script: main.app

- url: /api/accounts
  script: main.app

- url: /api/account/(.*)
  script: main.app

- url: /api/award(.*)

- url: /recover
  script: main.app

- url: /
  static_dir: frontend/public

skip_files: 
- ^(.*/)?.*/node_modules(/.*)?
- ^(.*/)?.*/build/(/.*)?
